services:
  enset-discovery-service:
    build: ./Discovery-Service
    container_name: enset-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 4
  enset-config-service:
    build: ./Config-Service
    container_name: enset-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      enset-discovery-service:
        condition: service_healthy
  enset-customer-service:
    build: ./Customer-Service
    container_name: enset-customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-config-service:9999
    depends_on:
      enset-config-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
  enset-account-service:
    build: ./Account-Service
    container_name: enset-account-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-config-service:9999
    depends_on:
      enset-customer-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8082/actuator/health" ]
      interval: 10s
      retries: 4
  enset-gateway-service:
    build: ./Gateway-Service
    container_name: enset-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-config-service:9999
    depends_on:
      enset-config-service:
        condition: service_healthy
  frontend-angular:
    build: ./Angular-Frontend
    container_name: frontend-angular
    ports:
      - '80:80'
    expose:
      - '80'